### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by haiquangtran** [haiquangtran/SpreadsheetApp#3]
- [ ] Parse nested functions (SUM(SUM()) etc) for equations
- [ ] Parse brackets for equations
- [x] Responsive table
- [x] add requireJS 
- [ ] show correct errors
- [x] Make pretty (mouse pointer etc)
- [ ] Tests
- [x] Alignment functionality
- [ ] Cell selection via mouse (selection of multiple cells etc)

**Comment by haiquangtran** [comment]
Parsing techniques: 
http://www.engr.mun.ca/~theo/Misc/exp_parsing.htm
